site_name: 太極拳論/經

site_url: http://myseq.github.io/69docs
site_author: zd
site_description: >-
  Write any note or documentation in Markdown and create a professional static site

repo_name: myseq/69docs
repo_url: https://github.com/myseq/69docs

# Copyright
copyright: Copyright &copy; 2024 zd


# Configuration
theme:
  name: material
  palette:

    # Palette toggle for dark mode (default)
    - scheme: slate
      accent: lime
      primary: amber
      toggle:
        icon: material/brightness-4
        icon: material/weather-sunny
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: light
      accent: indigo
      primary: black
      primary: light blue
      toggle:
        icon: material/brightness-7
        icon: material/weather-night
        name: Switch to dark mode

  icon: 
    logo: fontawesome/solid/yin-yang
    favicon: material/yin-yang 

  font:
    text: Fira
    code: Fira Mono

  features:
    - navigation.footer
      #    - navigation.tabs
      #    - navigation.tabs.sticky

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra:
  social:
    - icon: simple/github
      link: https://github.com/myseq/






